### ISSUE TITLE
Support for IStandardToken256

### ISSUE THREAD

**Issue by drmathias** [stratisproject/UnrealEnginePlugin#1]
It looks as though this is supporting the old IStandardToken contract. Support for IStandardToken256 will allow developers to use tokens in their games that can be traded on Opdex.

**Comment by madrazzl3** [comment]
Implemented: https://github.com/stratisproject/UnrealEnginePlugin/blob/2bdad678e7427cb8e3161944de62addd39541e79/Source/Stratis/Public/Wrappers/Testnet/UStandartTokenWrapper256.h
