### ISSUE TITLE
When recompiling to new Engine version It throws following error

### ISSUE THREAD

**Issue by Lingesuwaran** [stratisproject/UnrealEnginePlugin#3]
Log

E:\Unreal Engine\UE_4.27\Engine\Build\BatchFiles>RunUAT.bat BuildPlugin -plugin="C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis.uplugin" -package="C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis_SDK"
Running AutomationTool...
Parsing command line: BuildPlugin -plugin=C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis.uplugin -package=C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis_SDK
Copying 15328 file(s) using max 64 thread(s)
Reading plugin from C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis_SDK\HostProject\Plugins\Stratis\Stratis.uplugin...
Building plugin for host platforms: Win64
Running: E:\Unreal Engine\UE_4.27\Engine\Binaries\DotNET\UnrealBuildTool.exe UE4Editor Win64 Development -Project=C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis_SDK\HostProject\HostProject.uproject -plugin=C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis_SDK\HostProject\Plugins\Stratis\Stratis.uplugin -iwyu -noubtmakefiles -manifest=C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis_SDK\HostProject\Saved\Manifest-UE4Editor-Win64-Development.xml -nohotreload -log="C:\Users\ACER\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+Engine+UE_4.27\UBT-UE4Editor-Win64-Development.txt"
  ERROR: Unable to determine UHT module type for C:\Users\ACER\Downloads\UnrealEnginePlugin-master2\Stratis\Stratis_SDK\HostProject\Plugins\Stratis\Source\Blockchain\Blockchain.Build.cs
Took 7.4039298s to run UnrealBuildTool.exe, ExitCode=6
UnrealBuildTool failed. See log for more details. (C:\Users\ACER\AppData\Roaming\Unreal Engine\AutomationTool\Logs\E+Unreal+Engine+UE_4.27\UBT-UE4Editor-Win64-Development.txt)
AutomationTool exiting with ExitCode=6 (6)
BUILD FAILED

**Comment by madrazzl3** [comment]
The plugin was built and tested with Win10 x64 and UE 4.27, so I think there is a problem with cached files from previous builds. You can try to setup your project from the ground, or delete Binaries\ and Intermediates\ directories both from project's and plugin's path (in your case: HostProject\Binaries, HostProject\Plugins\Stratis\Binaries, HostProject\Intermediates, and HostProject\Plugins\Stratis\Intermediates)

**Comment by Lingesuwaran** [comment]
I didn't even integrate it with my game.
It just said it is only compactible with previous version of unreal so I tried recompiling it
